[package]
name = "day6"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
bencher.workspace = true

[lib]
name = "day6"
path = "src/lib.rs"

[[bin]]
name = "day6"
path = "src/main.rs"

[[bench]]
name = "speed"
harness = false
